### ISSUE TITLE
Failed to load the ide-gopls package

### ISSUE THREAD

**Issue by xtgoxa** [MordFustang21/ide-gopls#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [ide-gopls](https://github.com/MordFustang21/ide-gopls) package 0.2.1

### Stack Trace

Failed to load the ide-gopls package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.42.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:146745)
    at /packages/ide-gopls/lib/main.js:3:5)
    at /packages/ide-gopls/lib/main.js:100:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:1:728962)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3328046)
    at measure (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3314586)
    at Package.measure (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3313418)
    at Package.load (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3314159)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:381121)
    at config.transact (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:379544)
    at Config.transact (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:331609)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:379482)
    at t.loadState.then (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:1:749573)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-go 0.1.0 
atom-ide-ui 0.13.0 
atom-languageclient 0.9.9 
atom-material-syntax 1.0.8 
simplified-chinese-menu 5.3.5 
ide-go 0.12.3 
ide-gopls 0.2.1 
```

**Comment by stamblerre** [comment]
Does this issue occur when you install this package or when you try to build from source?

**Comment by MordFustang21** [comment]
I was able to setup a project on windows successfully using atom to install all the packages. I'm going to close this for now. Feel free to reopen if this is still happening or you're encountering this by installing from another source.
